config/routes.rb
Rails.application.routes.draw do

devise_for :users


  resources :users, only: [:update, :show, :index] do
    resources :friendships, only: [:create, :destroy]
    resource :wall
  end

   resources :users do
     member do
      get :following, :followers
     end
   end
   
  resources :users do
    resources :pages
    resources :collaborations
  end

  resources :todoos do
    resources :comments
  end

  resources :pages do
    resources :documents
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :supporting, :supporters
    end
  end
 
  resources :collaborations, only: [:create, :destroy]

  resource :wall do
    resource :topics
    resources :posts
  end
  
  resources :topics do
    resources :posts, controller: 'topics/posts'
    resource :wall
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resource :wall
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :todoos
  resources :subscribe
  resources :relationships, only: [:create, :destroy]
  resources :votes, only: [:create]
  resources :comments
  resources :documents
  

  get 'about' => 'welcome#about'
 
 authenticated :user do
    root 'topics#index', as: 'authenticated_root'
  end
 
  root to: 'welcome#index'

  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
   

  # searchable do
  #   text :title, :boost => 5
  #   text :content
  # end

  def up_votes
    votes.where(value: 1).count
  end

   def down_votes
     votes.where(value: -1).count
   end
   
   def points
     self.votes.sum(:value).to_i
   end
   

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
   
  def index
    @topic = Topic.new
    @topics = Topic.all
    @posts = Post.all
    @post = Post.find(params[:id])
      authorize @post
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @posts = @topic.posts
    @comments = @post.comments
    @comment = Comment.new  
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
      authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
      authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params.require(:post).permit(:image, :title, :id, :post_id, :image, :kind, :content))
    @post.topic = @topic
      authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
      authorize @post
    if @post.update(params.require(:post).permit(:title, :image, :kind, :content))
      flash[:notice] = "Post was updated."
      redirect_to topic_post_path
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @topic = @post.topic
    title = @post.title
    authorize @post
    if @post.destroy
      flash[:notice] = "post was deleted successfully"
      
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
helper_method :sort_column, :sort_direction

  def index
   @topic = Topic.new
   @topics = Topic.all
   @posts = Post.all
  
  end

  def new
    @topic = Topic.new
  end
  
  def show
    @topics = Topic.paginate(page: params[:page], per_page: 10)
    @topic = Topic.find(params[:id])
    @posts = @topic.posts

    # @topics = Topic.paginate(page: params[:page], per_page: 10)
    # @topic = Topic.find(params[:id])
    # @post = Post.find(params[:post_id])
    # @posts = @topic.posts
    # @comments = @post.comments
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic = Topic.find(params[:id])
    title = @topic.title
    
    if @topic.destroy
      flash[:notice] = "\"#{title}\" was deleted."
      redirect_to topics_path
    else
      flash[:error] = "Error with deleting topic. Please try again."
      render :show
    end
  end

  def create
    @topic = Topic.new(topic_params)
    
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end
   
  def update
    @topic = Topic.find(params[:id])
    
    if @topic.update_attributes(params.require(:topic).permit(:title, :id, :content))
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end

  private

    def topic_params
      params.require(:topic).permit(:title, :topic_id, :id, :content)
    end

    def sort_column
      Topic.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end


end

app/helpers/topics_helper.rb
module TopicsHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
  
end

app/views/topics/_form.html.erb
<div class="col-md-8">
    <%= form_for @topic do |f| %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>


      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      
      <%= f.submit "Save", class: 'btn btn-success' %>
   <% end %>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Is the topic is appropriate.</li>
      <li>Never insult anyone.</li>
      <li>Focus and type.</li>
    </ul>
  </div>
<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>
</div>



  

app/views/topics/index.html.erb
<div class="page-header">
  <center><strong><h3 id= "myToolTip" data-toggle="tooltip" title="Click on a Topic title to view all of the posts for that Topic."> HRKin Topics </h3></strong><small>select topic to create post</small>     
  </center>
</div>
<% @topics.each do |topic| %>
     <%= link_to topic.title, topic_path(topic), :class => 'btn btn-default alert alert-default'   %>
<% end %>
<br>
<% if user_signed_in? && current_user.admin? %>   
 <%= link_to 'New Topic', new_topic_path, class: 'btn btn-primary alert alert-success'  %>
 <% end %>
<hr>
<div class="page-header">
  <center><strong><h1 id= "myToolTip" data-toggle="tooltip" title="Click on a title to view the post."> Top HRKin Posts </h1></strong> 
  </center>
</div>


<table id="postindex" class="table table-hover" >
  <thead>
    <tr>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by title"><button type="button" class="btn btn-primary">Title</button></th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by points"><button type="button" class="btn btn-primary">Point</button></th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by User: Year-Month-Day"><button type="button" class="btn btn-primary">User</button></th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by date"><button type="button" class="btn btn-primary">Date</button></th>
    </tr>
  <thead>
  <tbody>
   <% @posts.each do |p| %>
    <tr>
      <td > <%= image_tag(p.image.thumb.url) if p.image? %>
      <strong><%= link_to p.title,[p.topic, p] %> </strong></td>
      <td ><%= p.points %></td> 
      <td ><%= image_tag(p.user.avatar.small.url, class: "img-circle") if p.user.avatar? %> <%=p.user.handle %></td> 
      <td ><%= p.created_at.strftime "%Y-%m-%d " %></td>
     </tr>
   <% end %>
  <tbody>
</table>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<h1> <%= @topic.title %></h1>&nbsp<%= link_to 'Back', topics_path, class: 'btn btn-primary alert alert-info' %>
<% if user_signed_in? && current_user.admin? %>
        <%= link_to 'Edit', edit_topic_path, class: 'btn btn-primary  alert alert-info' %>
       <%= link_to "Delete Topic", @topic, :method => :delete, class: 'btn btn-danger alert alert-info', :confirm => 'are you sure you want to delete' %> 
<%end %>
<hr>

<table id="postindex" class="table table-hover" >
  <thead>
    <tr>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by title"><button type="button" class="btn btn-primary">Title</button>&nbsp;&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by points"><button type="button" class="btn btn-primary">Point</button>&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by date: Year-Month-Day"><button type="button" class="btn btn-primary">Date</button>&nbsp;&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by comment count"><button type="button" class="btn btn-primary">Comment</button>&nbsp;&#8661;</th>
    </tr>
  <thead>
  <tbody>
   <% @posts.each do |post| %>
    <tr>
      <td > <%= image_tag(post.image.thumb.url) if post.image? %><strong><%=  link_to post.title,[@topic, post] %></strong></td>
      <td ><%=pluralize(post.points, 'point') %></td> 
      <td ><%= post.created_at.strftime "%Y-%m-%d " %></td>
      <td ><%=pluralize(post.comments.count,'comment') %></td> 
    </tr>
   <% end %>
  <tbody>
</table>
<br>

<%= link_to 'New Post', new_topic_post_path(@topic, @post), class: 'btn btn-primary alert alert-info' %> 
    
     