config/routes.rb
Rails.application.routes.draw do

devise_for :users


  resources :users, only: [:update, :show, :index] do
    resources :friendships, only: [:create, :destroy]
    resource :wall
  end

   resources :users do
     member do
      get :following, :followers
     end
   end
   
  resources :users do
    resources :pages
    resources :collaborations
  end

  resources :todoos do
    resources :comments
  end

  resources :pages do
    resources :documents
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :supporting, :supporters
    end
  end
 
  resources :collaborations, only: [:create, :destroy]

  resource :wall do
    resource :topics
    resources :posts
  end
  
  resources :topics do
    resources :posts, controller: 'topics/posts'
    resource :wall
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resource :wall
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :todoos
  resources :subscribe
  resources :relationships, only: [:create, :destroy]
  resources :votes, only: [:create]
  resources :comments
  resources :documents
  

  get 'about' => 'welcome#about'
 
 authenticated :user do
    root 'topics#index', as: 'authenticated_root'
  end
 
  root to: 'welcome#index'

  
end

app/models/post.rb
class Post < ActiveRecord::Base
 
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :votes, dependent: :destroy
  belongs_to :user
  scope :reverse_relationships, ->(followers) { where user_id: followers }
  belongs_to :topic
    mount_uploader :image, ImageUploader
    
  # validates :content, length: {minimum: 20}, presence: true
  # searchable do

  #   text :title, :boost => 5
  #   text :content
  #   text :comments do
  #     comments.map(&:content)
  #   end 
  #   integer :topic_id do
  #     topic.id 
  #   end
  #  end

  def up_votes
    votes.where(value: 1).count
  end

   def down_votes
     votes.where(value: -1).count
   end
   
   def points
     self.votes.sum(:value).to_i
   end

   def update_rank
    age = (created_at - Time.new(1970,1,1)) / (60 * 60 *24)
    new_rank = points + age
    update_attribute(:rank, new_rank)
   end


  default_scope { order('created_at DESC') }
  scope :visible_to, -> (user) {user ? all : joins(topic).where('topics.public' => true)}

  validates :title, length: {minimum: 5}, presence: true

  private

  def create_vote
    user.votes.create(value: 1, post:self)
  end 
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
   

  # searchable do
  #   text :title, :boost => 5
  #   text :content
  # end

  def up_votes
    votes.where(value: 1).count
  end

   def down_votes
     votes.where(value: -1).count
   end
   
   def points
     self.votes.sum(:value).to_i
   end
   

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 def index
   @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
 end
 
 def show
   @topic = Topic.find(params[:topic_id])
   @post = Post.find(params[:id])
   @comments = @post.comments
   @comment = Comment.new
 end
  
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
   
  def index
    @topic = Topic.new
    @topics = Topic.all
    @posts = Post.all
    @post = Post.find(params[:id])
      authorize @post
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @posts = @topic.posts
    @comments = @post.comments
    @comment = Comment.new  
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
      authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
      authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params.require(:post).permit(:image, :title, :id, :post_id, :image, :kind, :content))
    @post.topic = @topic
      authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
      authorize @post
    if @post.update(params.require(:post).permit(:title, :image, :kind, :content))
      flash[:notice] = "Post was updated."
      redirect_to topic_post_path
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @topic = @post.topic
    title = @post.title
    authorize @post
    if @post.destroy
      flash[:notice] = "post was deleted successfully"
      
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
helper_method :sort_column, :sort_direction

  def index
   @topic = Topic.new
   @topics = Topic.all
   @posts = Post.all
  
  end

  def new
    @topic = Topic.new
  end
  
  def show
    @topics = Topic.paginate(page: params[:page], per_page: 10)
    @topic = Topic.find(params[:id])
    @posts = @topic.posts

    # @topics = Topic.paginate(page: params[:page], per_page: 10)
    # @topic = Topic.find(params[:id])
    # @post = Post.find(params[:post_id])
    # @posts = @topic.posts
    # @comments = @post.comments
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic = Topic.find(params[:id])
    title = @topic.title
    
    if @topic.destroy
      flash[:notice] = "\"#{title}\" was deleted."
      redirect_to topics_path
    else
      flash[:error] = "Error with deleting topic. Please try again."
      render :show
    end
  end

  def create
    @topic = Topic.new(topic_params)
    
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end
   
  def update
    @topic = Topic.find(params[:id])
    
    if @topic.update_attributes(params.require(:topic).permit(:title, :id, :content))
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end

  private

    def topic_params
      params.require(:topic).permit(:title, :topic_id, :id, :content)
    end

    def sort_column
      Topic.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end


end

app/helpers/posts_helper.rb
module PostsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
  
end

app/views/topics/posts/_form.html.erb
<br>
<%= form_for [@topic, @post] do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There was an error </h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(@post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(@post.errors[:content]) do %>
    <%= f.label :content %>
    <%= f.text_area :content, rows: 8, class: 'form-control', placeholder: "Enter post content" %>
  <% end %>
  <% if @post.image? %>
    <div class="form-group">
      <p>Current image</p>
      <%= image_tag(@post.image.picture.url) %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/posts/_post.html.erb
  <div class="row">
    <div class="col-md-8">  
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
           <%= @post.title %> 
        <span class="user_avatars ">
         <%= image_tag(post.user.avatar.small.url, class: "img-circle") if post.user.avatar? %>
        </span>
         <small> by &nbsp <%= link_to post.user.handle,[@post.user, @user] %> </small> 
       </h4>
        </div>
      </div> 
      <%= image_tag(@post.image.picture.url) %>
        <br>  
      <% if post.kind == 'image' %>
        <%= image_tag post.content, style: "width: 100%" %> 
      <% else %>
        <%= @post.content %> 
      <% end %>
       <br> 
       <br> 
       <% if policy(@post).edit? %>
        <%= link_to 'Edit Post', edit_topic_post_path(@topic, @post), class: 'btn btn-primary' %>
       <% end %>
       <% if policy(@post).destroy? %>
         <%= link_to "Delete Post",[@topic, @post], :method => :delete, class: 'btn btn-primary', :confirm => 'are you sure you want to delete' %> 
       <% end %>
    </div>
  </div>
   <br>
 


  

app/views/topics/posts/edit.html.erb
<h1>Editing post</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for post:</p>
    <ul>
      <li>Is the topic is appropriate.</li>
      <li>Never insult anyone.</li>
      <li>Focus and type.</li>
    </ul>
 
<%= render 'form' %>

<%= link_to 'Show', topic_post_path(@topic, @post) %> |
<%= link_to 'Back', topics_path %>
</div>
</div>

app/views/topics/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/posts/show.html.erb
<%= render partial: 'post', locals: {post: @post, comment: @comment} %>

<%= render :partial => "/votes/vote", locals: {post: @post, vote: @vote } %>

  <div>
    <small>
      <%= pluralize(@post.up_votes, 'up vote') %>,
      <%= pluralize(@post.down_votes, 'down vote') %>
        <div class='js-comments-count'>
         </div>

    </small>

  </div>
  <br>
    <%= link_to 'All topics', topics_path %>
    &nbsp
    <%= link_to 'Go back to Topic',topic_path(@topic) %>
 <div>
  <br>
  <hr>
    <h3> Comments:</h3>
      <p class="italic"> <%= pluralize(@comments.count,'comment') %> </p>
 
 </div>
 <table>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %><small> <i>created on </i> 
           <%=comment.created_at.to_formatted_s(:short) %><br></small> 
        <% if policy(@comment).destroy? %>, @user
        <%= link_to "Delete",[@post, comment], :method => :delete, class: 'btn btn-success' 'alert alert-success', :confirm => 'are you sure you want to delete' %> 
         <% end %>
          <hr>
        
        </td>
      </tr>
    <% end %>
  </tbody>
 </table>

  <br>
 <div>
    <div class= 'new-comment'>
      <%= render :partial => "comments/form", locals: {post: @post, comment: @comment} %>
    </div>
  </div>

  