config/routes.rb
Rails.application.routes.draw do

devise_for :users


  resources :users, only: [:update, :show, :index] do
    resources :friendships, only: [:create, :destroy]
    resource :wall
  end

   resources :users do
     member do
      get :following, :followers
     end
   end
   
  resources :users do
    resources :pages
    resources :collaborations
  end

  resources :todoos do
    resources :comments
  end

  resources :pages do
    resources :documents
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :supporting, :supporters
    end
  end
 
  resources :collaborations, only: [:create, :destroy]

  resource :wall do
    resource :topics
    resources :posts
  end
  
  resources :topics do
    resources :posts, controller: 'topics/posts'
    resource :wall
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resource :wall
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :todoos
  resources :subscribe
  resources :relationships, only: [:create, :destroy]
  resources :votes, only: [:create]
  resources :comments
  resources :documents
  

  get 'about' => 'welcome#about'
 
 authenticated :user do
    root 'topics#index', as: 'authenticated_root'
  end
 
  root to: 'welcome#index'

  
end

app/models/post.rb
class Post < ActiveRecord::Base
 
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :votes, dependent: :destroy
  belongs_to :user
  scope :reverse_relationships, ->(followers) { where user_id: followers }
  belongs_to :topic
    mount_uploader :image, ImageUploader
    
  # validates :content, length: {minimum: 20}, presence: true
  # searchable do

  #   text :title, :boost => 5
  #   text :content
  #   text :comments do
  #     comments.map(&:content)
  #   end 
  #   integer :topic_id do
  #     topic.id 
  #   end
  #  end

  def up_votes
    votes.where(value: 1).count
  end

   def down_votes
     votes.where(value: -1).count
   end
   
   def points
     self.votes.sum(:value).to_i
   end

   def update_rank
    age = (created_at - Time.new(1970,1,1)) / (60 * 60 *24)
    new_rank = points + age
    update_attribute(:rank, new_rank)
   end


  default_scope { order('created_at DESC') }
  scope :visible_to, -> (user) {user ? all : joins(topic).where('topics.public' => true)}

  validates :title, length: {minimum: 5}, presence: true

  private

  def create_vote
    user.votes.create(value: 1, post:self)
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 def index
   @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
 end
 
 def show
   @topic = Topic.find(params[:topic_id])
   @post = Post.find(params[:id])
   @comments = @post.comments
   @comment = Comment.new
 end
  
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
   
  def index
    @topic = Topic.new
    @topics = Topic.all
    @posts = Post.all
    @post = Post.find(params[:id])
      authorize @post
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @posts = @topic.posts
    @comments = @post.comments
    @comment = Comment.new  
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
      authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
      authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params.require(:post).permit(:image, :title, :id, :post_id, :image, :kind, :content))
    @post.topic = @topic
      authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
      authorize @post
    if @post.update(params.require(:post).permit(:title, :image, :kind, :content))
      flash[:notice] = "Post was updated."
      redirect_to topic_post_path
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @topic = @post.topic
    title = @post.title
    authorize @post
    if @post.destroy
      flash[:notice] = "post was deleted successfully"
      
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/posts/_form.html.erb
<br>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>HRkin Posts</h1>

<% if policy(Post.new).create? %>
  <%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
<% end %>

<% @posts.each do |post| %>
  <div class="media">
   <%= render partial: 'votes/vote', locals: { post: post} %>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to post.title %>
      </h4>
      <h5>
        <%= @post %>
      </h5>
      <small>
        submitted by <%= @post.username %> <%= time_ago_in_words(post.created_at) %> ago 
      </small>
      <%= link_to 'Back', posts_path(@topic,@post) %>
       <%= link_to 'New Post', new_post_path(@topic,@post), class: 'btn btn-success' 'alert alert-success' %>
      <%= will_paginate @posts %>
    </div>
  </div>
<% end %>
<br>


 

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <small>
    <%= image_tag(@post.user.avatar.small.url, class: "img-circle") if @post.user.avatar? %>
     submitted <%= time_ago_in_words(@post.created_at) %> ago by
     <%= @post.user.name %>
  </small>
  <%= @post.content %>
</p>
  <small>
    submitted by <%= @post.username %> <%= time_ago_in_words  post.created_at) %> ago 
  </small>
  <%= link_to 'Edit', edit_post_path(@post) %> 
 <%= render partial: "comments/comment", locals: {topic: @topic, post: @post, comment: @comment} %> 
<%= link_to 'Edit', edit_comment_path(@comment) %> 
<%= link_to 'Back', posts_path %>