config/routes.rb
Rails.application.routes.draw do

devise_for :users


  resources :users, only: [:update, :show, :index] do
    resources :friendships, only: [:create, :destroy]
    resource :wall
  end

   resources :users do
     member do
      get :following, :followers
     end
   end
   
  resources :users do
    resources :pages
    resources :collaborations
  end

  resources :todoos do
    resources :comments
  end

  resources :pages do
    resources :documents
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :supporting, :supporters
    end
  end
 
  resources :collaborations, only: [:create, :destroy]

  resource :wall do
    resource :topics
    resources :posts
  end
  
  resources :topics do
    resources :posts, controller: 'topics/posts'
    resource :wall
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resource :wall
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :todoos
  resources :subscribe
  resources :relationships, only: [:create, :destroy]
  resources :votes, only: [:create]
  resources :comments
  resources :documents
  

  get 'about' => 'welcome#about'
 
 authenticated :user do
    root 'topics#index', as: 'authenticated_root'
  end
 
  root to: 'welcome#index'

  
end

app/models/todoo.rb
class Todoo < ActiveRecord::Base

 belongs_to :user
 
  def countdown
    (7 - (Date.today - created_at.to_date)).to_i
  end

  

end

app/controllers/todoos_controller.rb
class TodoosController < ApplicationController
  #before_filter :authenticate_user!

  def index
    # if !current_user.subscribed
    #   redirect_to new_subscribe_path, :notice => "to view the Todoo you must subscribe"
    #  end
    @todos = current_user.todoos.where(done: false)
    @todone = current_user.todoos.where(done: true)
    @alldone = Todoo.all.where(done: true)
     
  end

  def new
    @todo = Todoo.new
  end

  def create
    @todo = current_user.todoos.build(todo_params)
    if @todo.save
      redirect_to todoos_path, :notice => "Your todo item was created!"
    else
      render "new"
    end
  end

  def update
    @todo = Todoo.find(params[:id])
    if @todo.update_attribute(:done, true)
      redirect_to todoos_path, :notice => "Your todo item was marked as done!"
    else
      redirect_to todoos_path, :notice => "Your todo item was not properly marked!"
    end
  end

  def destroy
    @todo = Todoo.find(params[:id])
    @todo.destroy
    redirect_to todoos_path, :notice => "Your todo was deleted"
  end

  private
  def todo_params
    params.require(:todoo).permit(:name, :content, :done, :user, :user_id)
  end

end

app/views/todoos/index.html.erb
  <center><strong><h1> HRkin ToDo items </h1></strong></center>
  <br>


<%= link_to 'Your ToDo list', '', id: 'myTodolist', class: 'btn btn-success btn-lg' %>
<div class= "myTodolist hidden" >

<div id= "myToolTip" data-toggle="tooltip" title="Tip: only add task that are specfic and will not take too much time to complete, in other words... go for the small wins" >
<h2> What you need to-do: </h2> </div>
<h5> You have <%=@todos.count %> item(s) on your "To-do" list.</h5>
 

<table id="postindextodo" class="table table-hover" >
  <thead>
    <tr>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by tasks"><button type="button" class="btn btn-primary">Task</button>&nbsp;&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Countdown of 7 days"><button type="button" class="btn btn-primary"> Countdown</button>&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by date: Year-Month-Day"><button type="button" class="btn btn-primary">Date</button>&nbsp;&#8661;</th>
      <th></th>
    </tr>
  <thead>
  <tbody>
   <% @todos.each do |t| %>
  <tr>
    <td ><strong><ul><li><%= t.name %></li></ul></strong></td>
    <td ><%= t.countdown %> days left!</td> 
    <td ><%= t.created_at.strftime "%Y-%m-%d %h"  %></td>
    <td > <%= link_to 'Mark as Done', todoo_path(t), 
    :method => :put %> </td> 
  </tr>
    <% end %>
  <tbody>
</table>

<p><%= link_to 'Add item to the list', new_todoo_path, class: 'btn btn-success' 'alert alert-success' %> </p>
</div>

 <br>
 <hr>


<%= link_to 'Your Done list', '', id: 'myTodonelist', class: 'btn btn-success btn-lg' %>
<div class= "myTodonelist hidden" >
<div id= "myToolTip" data-toggle="tooltip" title="congratulations!" >
 <h2>Done: </h2> </div>
<h5> You have <%=@todone.count %> item(s) on your "Done" list.</h5>
<% @todone.each do |t| %>
  <p>
    <ul><li><strong><%= t.name %></strong>&nbsp<small> <%= link_to 'Remove', t, :confirm => "Are you sure you want to delete?", :method => :delete %> </small></li></ul>
    
  </p>
  <hr>
<%end%>
</div>
 
 <br>
 <hr>



<%= link_to 'What others did', '', id: 'myTodoworldlist', class: 'btn btn-success btn-lg' %>
<div class= "myTodoworldlist hidden" >
<h4><center><%= pluralize(@alldone.where("updated_at >= ?", Time.zone.now.beginning_of_day).count ,'task')%> done today throughout the HRKin World!</center></h4>

<table id="postindex" class="table table-hover" >
  <thead>
    <tr>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by tasks"><button type="button" class="btn btn-primary">Task</button>&nbsp;&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Completed on"><button type="button" class="btn btn-primary"> Done on</button>&#8661;</th>
      <th><id: "myToolTip" data-toggle="tooltip" title="Sort by user"><button type="button" class="btn btn-primary">User</button>&nbsp;&#8661;</th>
     
    </tr>
  <thead>
  <tbody>
   
  <% @alldone.each do |t| %>
   <tr>
     <td ><%= image_tag(t.user.avatar.small.url, class: "img-circle") %>
      <strong><%= t.name %></strong></td>
     <td> <%= t.updated_at.strftime "%Y-%m-%d " %></td>
     <td> <%= t.user.handle %></td>
   </tr>
     <% end %>
  <tbody>
</table>
</div>

app/views/todoos/new.html.erb
<h1> Add new item to your todo list </h1>

<%= form_for @todo, url: {action: "create"} do |f| %>
  
   <div class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name, placeholder: "short description of task" %>
    <%= f.hidden_field :done, :value => false %>
    <%= f.submit "Add to the to-do list", class: 'btn btn-primary'  %>
   </div>
<% end %>

app/views/todoos/show.html.erb
<h3><%= @todo.name %></h3>
 
<p><%= link_to "Back to Todo", todoos_path %></p>

<h4>Comments</h4>
<%= @comments.count %> comments

<table>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content  %></td>    
      </tr>
    <% end %>
  </tbody>
</table>

<%= render "comments/form" %>